refactor: modernize codebase and drop dependencies
electron/unreleased pull request #110
Opened 2024-10-03 23:01 UTC by dsanders11

Drops several packages in favor of using builtins in modern Node.js, most notably `node:test`.

Will follow this up with a PR to update the remaining dependencies, I just didn't want to blow this one out with any formatting changes that may occur as a result. I had to update `eslint` in this PR so it understood builtin `fetch`.

2024-10-04 15:04 UTC, jkleinsc requested changes
postToSlack needs to handle the async fetch

2024-10-04 15:04 UTC, jkleinsc commented on utils/helpers.js
> +  fetch(postUrl, {
```suggestion
  await fetch(postUrl, {
```

2024-10-04 16:53 UTC, dsanders11 commented on utils/helpers.js
> +  fetch(postUrl, {
Good catch! Small oversight there.

2024-10-10 08:25 UTC, codebytere approved these changes

2024-10-15 16:07 UTC, jkleinsc approved these changes

2024-10-15 16:08 UTC, merged